language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"    
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true

script: python app.py || python3 app.py
